### ISSUE TITLE
Duplicate entries in global stream

### ISSUE THREAD

**Issue by fenriques** [astrobin/astrobin#1342]
A small issue: when browsing  images in the home page and global stream is selected (that seems to be the default filter), multiple copies of the same image are shown. 
See image below

![Screenshot from 2020-10-01 18-02-53](https://user-images.githubusercontent.com/38842860/94834649-e8ffd400-0410-11eb-9d90-82b24c26f6d8.png)

**Comment by siovene** [comment]
Hi @fenriques, thanks for the report.

Does this happen also upon first load or only after more are loaded when you scroll down?

**Comment by fenriques** [comment]
didn't notice that before but you're right, it's only after the first 'page' is loaded (scrolling down or pressing 'more').

ferrante

**Comment by siovene** [comment]
This happens because when we load page 2, some new items have popped up on page 1, pushing that element down to page 2, so now it appears twice. It's a low-impact medium-effort thing to fix but I'll keep it in mind!

**Comment by fenriques** [comment]
ok. good to know!
