### ISSUE TITLE
Fix the text color contrast on the welcome page dropdown 

### ISSUE THREAD

**Issue by HunterHarling** [astrobin/astrobin#1520]
The text color of the mobile dropdown on the welcome page is currently black (difficult to see).

**Comment by siovene** [comment]
Thanks, I never noticed! Fixed.

<img width="266" alt="Screen Shot 2020-10-22 at 22 20 15" src="https://user-images.githubusercontent.com/891580/96925675-d11dec00-14b4-11eb-9a90-224b8ba4fdd1.png">
