### ISSUE TITLE
Top picks are off-center when screen width < 980px

### ISSUE THREAD

**Issue by HunterHarling** [astrobin/astrobin#1549]
![top-pick-center](https://user-images.githubusercontent.com/52986232/97731838-dff73680-1a92-11eb-8dc0-db624e6145bb.jpg)

**Comment by siovene** [comment]
Good catch! I also noticed that on smaller screens, like a phone, every other top pick has a small padding on the right side.

I propose that we try and still show them 2 by 2 from 768px and up.

Were you planning to tackle this @HunterHarling?

**Comment by HunterHarling** [comment]
Sure, I can do this one. 

>  2 by 2 from 768px and up.
Sounds good, I'll just resize them from 768-980 so that they remain side by side.
