### ISSUE TITLE
Staging area badge popup is blocked

### ISSUE THREAD

**Issue by HunterHarling** [astrobin/astrobin#1581]
![astrobin popup block](https://user-images.githubusercontent.com/52986232/98291433-fb18e900-1f5f-11eb-97dd-2396133fc8f6.png)

Looks like it has an incorrect z-index.

**Comment by siovene** [comment]
@HunterHarling no, it's actually that the container has `overflow: hidden`. We need to either move it out of that container or remove the popup, that's not really needed there.
