### ISSUE TITLE
Implement anonymized image detail page

### ISSUE THREAD

**Issue by siovene** [astrobin/astrobin#1656]
To be used in TP/IOTD and contexts.

**Comment by HunterHarling** [comment]
@siovene I could do this one, unless you're already working on it. 
Do you think that hiding the user detail panel and the comments would anonymize it enough? Also, I'm not sure what can be done about the watermark (unless there's a watermark-free version?).

**Comment by siovene** [comment]
Hi Hunter, this would be awesome. It's actually a rather massive task that represents the first step in migrating the image page to the Angular app.

It involves the following steps:

- Add a `secret`, in addition to the existing `hash` to the `Image` model (this is so the user cannot simply go to the non-anonymized page by copying the hash)
- Implement an image page in the Angular app. Since this is just for IOTD purposes, it can and should be simple (no like, no comments, no user info, etc): it should only have the image and the technical card.
- The image should be zoomable tho.

Since this task lays the foundation for the migration of the image page to the Angular app, of course it needs to be done properly and will require the creation of many new services that will be used for a long time on AstroBin.

If you feel up to the task, and your Angular is good, we can discuss the details!

PS: regarding the watermark, the watermark free image can already be generated, but first I need to add the possibility to use an image as a watermark, to avoid people stamping their name on it directly from Photoshop, and that I can't remove of course :)

**Comment by siovene** [comment]
@HunterHarling if you are intimidated by this task now, but would like to do something that I think is of paramount importance, would you like to write a bunch of Cypress integration tests? :) I would like to add more coverage for the main interactions like uploading and editing images, plus some basic website functionality like testing the main languages (I've had this fail in the past because of a bad translation) and so on. I already have the Cypress infrastructure in place in my CI/CD pipeline (except for the Angular app, which runs the tests on mocks but I want to change that).

**Comment by HunterHarling** [comment]
> Since this task lays the foundation for the migration of the image page to the Angular app, of course it needs to be done properly and will require the creation of many new services that will be used for a long time on AstroBin.

In this case, you should probably be the one to do it. I don't know Angular very well also, I usually use React for frontends.

I can write some Cypress tests though. If you make a list of features that need to be tested I could start on that.

**Comment by siovene** [comment]
I'm closing this issue, because this will be part, someday, of just porting the image page to Angular. This is not happening just for the IOTD or other contests because now the Angular app has the IOTD process ported to it, and instead of an anonymized page we just show the non-identifying information there.
