### ISSUE TITLE
Add more tests to Cypress suite

### ISSUE THREAD

**Issue by siovene** [astrobin/astrobin#1749]
The Cypress test suite should be more comprehensive, including as many tests as possible, at least for all the core functionalities.

Right now, it only does:

- [X] Login
- [X] Upload happy path
- [X] Some forum tests

I would like to add:

- [x] Registration
- [ ] Language switching (check for instance that a bunch of menu entries are translated after switching)
- [ ] More upload scenarios
- [x] More forum tests
- [x] Comments
- [x] Likes

A lot of other stuff is tested with Python tests that look at the HTML of the responses, so it's fine.

**Comment by siovene** [comment]
@HunterHarling when you want, this is here for you :) Let me know if you need help getting started!

**Comment by HunterHarling** [comment]
@siovene what other tests are needed for the forums besides like/unlike?

**Comment by siovene** [comment]
@HunterHarling the most common content editor functions, such as uploads, smileys, etc.

**Comment by siovene** [comment]
Moved to private issue tracking.
