### ISSUE TITLE
Add acquisition details to data export

### ISSUE THREAD

**Issue by siovene** [astrobin/astrobin#1786]
ZD#1586

**Comment by seadogger** [comment]
+1.  This would be a nice enhancement to add to the API.  Would first like to be able to pull the acquisition date.

Other items would be nice on the technical card to pull from the API as well.

**Comment by siovene** [comment]
This issue refers to the function that lets you download your data off astrobon in a big zip file, not the API.

**Comment by siovene** [comment]
Moved to private issue tracking.
