### ISSUE TITLE
Notification preferences are not accessible through site navigation

### ISSUE THREAD

**Issue by slavicd** [astrobin/astrobin#2022]
I believe there's no way to find a link to /notifications/settings/ from the site nav. If that is correct, I suggest adding one under settings.

**Comment by siovene** [comment]
Thanks for the issue report! There is a button on the notifications modal on the website. There is also a button on the page with the list of all notifications: https://app.astrobin.com/notifications

<img width="755" alt="Screenshot 2021-03-10 at 14 02 04" src="https://user-images.githubusercontent.com/891580/110633624-46126980-81a9-11eb-844e-796d995390ba.png">

<img width="1046" alt="Screenshot 2021-03-10 at 14 03 34" src="https://user-images.githubusercontent.com/891580/110633810-7eb24300-81a9-11eb-881a-b7fcae836f8a.png">

**Comment by slavicd** [comment]
Ha, you're right!
