### ISSUE TITLE
Inverted image

### ISSUE THREAD

**Issue by olivergs** [astrobin/astrobin#2256]
Hi there Salvatore.

I've noticed the inverted image feature has some delay when you asked for the inverted image. I suppose (haven't had time to check in the code) you are generating the image on the fly.

Just wanted to ask you if there is a special reason to do that server-side instead of using the invert filter of CSS

https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/invert()

If there is no special reason, this could help to avoid more CPU use on the servers, also, disk space.

If you want to use the CSS feature, I could try to find some time to send you a patch for this, but I can't promise.

**Comment by olivergs** [comment]
Current behavior is to go to view menu, select inverted and then the main image is the inverted and the hover one is the original.

You mean to change the behavior so if the user selects inverted, the main image is unchanged but the hover one is the inverted?

**Comment by siovene** [comment]
@olivergs I think it would be very confusing if you click on "View -> Inverted" and nothing actually happens unless you hover with the mouse.

**Comment by olivergs** [comment]
Of course. I Agree with you. I was asking because I did not understand what did you mean with:

"If you ever have time for this, I would suggest, instead, pre-generating the inverted image when a user specifies that the mouse-hover image should be the inverted view."

If you explain me the feature you want to do, maybe I could help.

**Comment by olivergs** [comment]
Ok. Now I understood. I did not know about the second option.

Yes, the easiest solution should be pre-generate the image then.

I will take a look to the code when I have some spare time and try to send you something.

Thanks
