### ISSUE TITLE
Reorganize static files and their usage

### ISSUE THREAD

**Issue by siovene** [astrobin/astrobin#469]
- Move astrobin's static files to `/astrobin/static/astrobin`
- Use the {% static %} tag thoroughly

**Comment by skaven81** [comment]
@siovene I can work on this one next if you'd like to assign it to me

**Comment by siovene** [comment]
Great, thanks!

**Comment by siovene** [comment]
@skaven81 if you haven't started with this, I'll take it. I need this changes for some work I'm doing on frontend optimizations.

**Comment by siovene** [comment]
Actually turns out I don't need it urgently, my pipeline modifications can do without this.

**Comment by skaven81** [comment]
I'm working under the idea that you want to manage static files "by the books", e.g. as described in https://docs.djangoproject.com/en/1.9/howto/static-files/
