### ISSUE TITLE
Add image category tags

### ISSUE THREAD

**Issue by siovene** [astrobin/astrobin#570]
To better categorize images and allow search filtering and category contests, a new field should be added to the `Image` class, with the following possible values:

- **Backyard**: an image acquired from your home
- **Travelling**: an image acquired by traveling to a location other than home. (This can include a single night out or a longer trip to astrofarm locations such as Namibia)
- **Remote**: an image acquired in your own remote observatory. If your observatory is in your backyard or home, please choose the "Backyard" category. If you need a car or other form of transportation to reach your observatory, then it counts as remote. If you partly own the equipment in the observatory, you can still select this option.
- **Downloaded**: an image for which you did not acquire the data yourself. You downloaded this from a remote observatory that you rented time on, a shared remote setup of which you own no equipment, any other type of public or private downloads, including AstroBin Public Data Pools, or a friend.
- **Professional**: an image whose data was downloaded from a professional observatory, such as the Hubble Legacy Archive or similar.
- **Mix**: an image whose data is a mix coming from any of the sources above
- **Other**: an image that does not fit in any of the above cateogories

Things to do:

- [x] Add the field to the model
- [x] Add the db migration
- [x] Make sure the field appears in the basic image setting form together with documentation
- [x] Add filtering to the Search and the Wall
- [x] Group Top Picks by the categories above

**Comment by skaven81** [comment]
The fact that there is some ambiguity between some of the options suggests that perhaps the options need to be revised a bit (ex. "Professional" and "Downloaded" is ambiguous).  The [MECE principle](https://en.wikipedia.org/wiki/MECE_principle) is a good approach to use for these kinds of things.

The idea is to be able to separate images into "buckets" for the purposes of IOTD awards and for general filtering.  It's worth keeping in mind that as you add buckets, the cross product of the buckets with other categories will be huge, and could make it difficult to create sane "classes" for IOTD competition.  So what are the attributes that materially affect the quality of the resulting image, and what is the fewest number of buckets that can accurately represent this?

Obviously, using data downloaded from an online archive should be its own bucket.  I don't think it is necessary to separate these into "professional" vs "downloaded" -- "downloaded" alone would be sufficient for this.  It captures the most important part of the bucket -- the associated user did not capture the raw data themselves.

For images using data captured by the user themselves, the two things that can materially affect the quality of the image (other than equipment used) are light pollution and imaging time.  Given there are two attributes, that makes four combinations:

* poor skies + short imaging time -- this is somebody that doesn't have a permanent setup and is imaging from their backyard.
* good skies + short imaging time -- somebody that lives under dark skies but doesn't have a permanent setup, and is imaging from their backyard
* poor skies + long imaging time -- permanent backyard observatory in a light polluted area
* good skies + long imaging time -- permanent backyard observatory in a dark area, or the user drove to a dark-sky site and stayed out all night capturing subs.

Can these four categories be described in a way that users will naturally fall into MECE?

The first is probably best described as "Backyard - temporary" and the third, "Backyard - permanent"

I'm thinking that it's probably reasonable to combine the second and fourth categories into one bucket, "Dark Sky" -- this captures those both driving to a dark sky location, and those that happen to be lucky enough to live under dark skies.

That simplifies the list down to just four resulting categories:

* Downloaded (images processed from data you did not collect yourself)
* Backyard - temporary (raw data captured under urban/suburban conditions, with equipment that has to be set up and broken down every time you want to image)
* Backyard - permanent (raw data captured under urban/suburban conditions, with permanently mounted equipment)
* Dark Sky - raw data captured under dark skies

I might even argue that the second and third categories should be combined, eliminating the "imaging time" part of the consideration.  After all, a dedicated astroimager with a tripod can set up multiple nights in a row and capture just as much data than somebody with an observatory.  If you ditch the "imaging time" part of the bucketizing, you simplify even more:

* Downloaded (images processed from data you did not collect yourself)
* Backyard (images taken under light polluted skies)
* Dark Sky (images taken under dark skies)

I don't think users would have any trouble conclusively selecting one of these categories.

Now, assuming it's just these three categories, are there any cases where users might feel they can't compete?

The "Travelling" category you propose is interesting, and probably deserves to be its own category.  Somebody with the resources to fly to Namibia with their astroimaging rig should probably not be competing for IOTD with somebody that can only afford to drive an hour to their club's dark sky site.  I suggest making "Travelling" specifically for images taken while "abroad" -- not at home or at a "local" dark sky site.

The other major aspects that create "fairness" in judging images against each other would be value of equipment used, and (in broad ranges) focal length used.  A beginner using an 80mm achromat with a DSLR on an unguided AVX mount should not be competing with somebody using an 80mm Tak with an SBIG cooled camera on a MyT mount.  Similarly, somebody shooting at 2000mm focal length shouldn't be competing with somebody shooting with a 50mm DSLR lens.  I imagine you will be coming up with categories for this type of grouping as well.  Matrixing these buckets together should yield "classes" within which people can more-or-less fairly compete for IOTD, and still provide useful search/filtering criteria.

**Comment by siovene** [comment]
I think that the confusion stems from the fact that I titled this issue "category tags", which is already a bit of an oxymoron. I consider categories to be Mutually Exclusive, and tags to allow overlapping. For instance the reason I added *Mix* was because some people mix their own data with downloaded data. That would not fit in a bucket as per the MECE principle.

I don't think that sky quality should be handled here: acquisition details have a Bortle scale field. The UI there should be improved a lot, tho. Honestly, the whole equipment and acquisition parts of the image upload and edit process will be redesigned. They were of course one of the first things I wrote in AstroBin, so they are the worst :-D

> The "Travelling" category you propose is interesting, and probably deserves to be its own category. Somebody with the resources to fly to Namibia with their astroimaging rig should probably not be competing for IOTD with somebody that can only afford to drive an hour to their club's dark sky site

By travelling, I didn't mean necessarily flying out to Namibia. 50% of AstroBin users travel to dark sites to image. I imagine that most of them mean that they load the car on Saturday afternoon, drive 2-3 hours to the mountains, spend the night imaging, and drive back home in the morning.

I agree tho that overlapping and ambiguity should be minimize. We also should not throw away data. For instance, yes: downloaded data is downloaded whether it come from DSW or Hubble, but it's easy to differentiate them, and one day that piece of data might turn out to be useful.

Value of equipment used will also be data that will be implicitly known or knowable by looking at what equipment the image was acquired from. I plan a new Equipment Module with curated data.

So, all that is left is the origin of the data. 

- Self acquired
    - Backyard
    - Traveller
    - Own remote observatory
- Downloaded
    - Amateur hosting facility
    - Public amateur data
    - Professional, scientific data
- Mix (because some people do it)
- Other (because you always need other)
