### ISSUE TITLE
Have pipeline generate the CSS from the LESS automatically, and uglify for production

### ISSUE THREAD

**Issue by siovene** [astrobin/astrobin#585]

**Comment by skaven81** [comment]
Perhaps MEDIA_VERSION could be generated as a hash of the static content in the same context?  That way we don't have to remember to tick MEDIA_VERSION when something changes.

**Comment by siovene** [comment]
Yeah, looks like it's easy with `pipeline`: http://django-pipeline.readthedocs.io/en/1.1.27/versioning.html
