### ISSUE TITLE
Development (local) Astrobin build, uploaded photos show as dead links

### ISSUE THREAD

**Issue by skaven81** [astrobin/astrobin#586]
Starting a new, local build of Astrobin and then uploading an image as astrobin_dev succeeds, but all references to the uploaded image appear as broken images.  Neither the thumbnail nor the full image appear in the gallery.

**Comment by siovene** [comment]
Works for me. Is your `astrobin.env` pristine, i.e. empty? Check the HTML with Chrome inspector: what is the broken `<img>`?

**Comment by skaven81** [comment]
I'll rebuild from scratch and see if I can reproduce it.

**Comment by skaven81** [comment]
I'm unable to reproduce this after doing a clean build.  Must have been an artifact of a prior failed build or something.
