### ISSUE TITLE
Add skyplot of image in API

### ISSUE THREAD

**Issue by HamHamFonFon** [astrobin/astrobin#687]
Hello,
I have a request : i would like to get the skyplots of an image who are displayed on each page and i don't kown how (event if it's possible). View that it's an image, is it possible to add path of this image in API '/api/v1/image/' ?
Or maybe there is an another way to get it :) ?
Thx

**Comment by siovene** [comment]
This is indeed not currently supported by the API. Thanks for the report!

**Comment by HamHamFonFon** [comment]
Thank you for answer.
This can't be added in the future in the API ? (in another endpoint or in image endpoint, no matter).

PS : if the API was coded in PHP, i would be happy to purpose this in pull request, unfortunately i don't know Python :/

**Comment by HamHamFonFon** [comment]
Thank you for this feature, i will watch #1707 and update https://github.com/HamHamFonFon/Astrobin-API-PHP as soon as possible
