### ISSUE TITLE
Investigate why AstroBin sends 0 bytes to Astrometry.net for this image

### ISSUE THREAD

**Issue by siovene** [astrobin/astrobin#868]
https://www.astrobin.com/forum/c/astrobin/forum-feedback/plate-solving-failing-with-this-files-type-is-not-supported-error-at-astrometrynet/

**Comment by fmeschia** [comment]
This seems to have been solved – I noticed today that astrometry.net solved https://www.astrobin.com/408432/F/ just fine, for the first time ever!

**Comment by siovene** [comment]
Yay!
