### ISSUE TITLE
Incorrect og:image meta-tag link causing FB sharing to be broken

### ISSUE THREAD

**Issue by cricke** [astrobin/astrobin#915]
Looking at e.g. https://www.astrobin.com/9l7794/ I notice it has the following meta tag (which returns a 404):
`<meta property="og:image" content="https://astrob.in/478206/0/rawthumb/regular/get.jpg?insecure">
`
Shouldn't it rather be:
`<meta property="og:image" content="https://astrob.in/9l7794/0/rawthumb/regular/get.jpg?insecure">`

Checked a few other images, and all seemed to have this problem, meaning sharing to e.g. FB is broken.

**Comment by siovene** [comment]
Thanks! Should be an easy fix, I'll fix ASAP.
